### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pboxed** [rostenkowski/imagestore#1]
Hi

Awesome script you made here! And sorry for abusing the issue tracker, I couldn't find another way to write you.

I just want to know if it is possible to fetch a group of images or the urls? For example for my site, I have multiple images for the same product and would like to fetch all image urls for a specific product in one take.

Regards,
pboxed

**Comment by rostenkowski** [comment]
Hi,
sorry for the late response. Currently there is not implemented the multiple URL fetching. You can try to use the `add()` method this way:

```php
foreach ([<LIST OF YOUR IMAGES URL>] as $url) {
    $meta = new <YOUR IMAGE ENTITY CLASS>();
    $storage->add(new File($url), $meta);
}
``` 

It is not tested behavior to download images from the URL, so please let me know if this works for you.  If you want something else please provide a more detailed use case.

**Comment by rostenkowski** [comment]
Hi,
sorry for the late response. Currently there is not implemented the multiple URL fetching. You can try to use the `add()` method this way:

```php
foreach ([<LIST OF YOUR IMAGES URL>] as $url) {
    $meta = new <YOUR IMAGE ENTITY CLASS>();
    $storage->add(new File($url), $meta);
}
``` 

It is not tested behavior to download images from the URL, so please let me know if this works for you.  If you want something else please provide a more detailed use case.

**Comment by rostenkowski** [comment]
So it is tested behaviour now. The above snippet should work as expected.
